### ISSUE TITLE
Add ability to customize font face

### ISSUE THREAD

**Issue by Phlarx** [Phlarx/tm-checkpoint-counter#5]
Add a setting to load and display with a user-defined font. Look to the Dashboard plugin for an implementation example.

Suggested by KevindeB#5500 in the OP discord.

**Comment by TheAaronator** [comment]
whenever i enter a new font, it doesn't change. Can you give an example of what exactly to type in to get the font to change?

**Comment by Phlarx** [comment]
@TheAaronator
🤔 that's a valid point

You need to put a font file into your Openplanet user folder, inside the `Fonts` folder (make it if it doesn't exist). E.g.: `C:\Users\<user>\OpenplanetNext\Fonts\somefont.ttf`

And then type the file name `somefont.ttf` into the plugin.

(I just made #7 to remind myself to add the info to the plugin on the next update)

**Comment by TheAaronator** [comment]
@Phlarx hmm, it still isn't working for me. The font is in the Openplanet folder. And I tried restarting the game too but the font still didn't change from the original one. Do you know what I might be doing wrong?

**Comment by Phlarx** [comment]
@TheAaronator The font needs to be in the Fonts folder, inside the Openplanet folder. If that is true, I'd suggest trying a different font.

If the other font does not work, then we can try debugging further (I could try making a testing script, for example).

If a different font does work, then there's an issue with that specific font file, and that should be reported to the Openplanet dev.

Edit: also, which game? So that I can try to test stuff on my end, too.

**Comment by TheAaronator** [comment]
@Phlarx  I'm playing the newest trackmania game. But it's all good, it turns out the 2 fonts I tried using just didn't work. But I downloaded a different font and it works now! Thank you for helping!! :)

**Comment by Phlarx** [comment]
@TheAaronator good to hear that it's working, thanks for the update!

I would highly recommend posting a report the broken fonts at https://github.com/openplanet-nl/issues/issues
It's posssible that they're just broken, but it might actually be a bug in Openplanet.
